#!/usr/bin/env bash
# Example clock

hours=0 
minutes=1

while [ $hours -le 12 ]
do
	echo Hour:$hours
	(( hours++ ))

	while [ $minutes -le 59 ]
	do
       		echo $minutes
		(( minutes ++ ))
	done
	minutes=1
done


