#!/usr/bin/env bash
#Process and PID file
trap 'rm /var/run/myscript.pid;exit' SIGQUIT SIGTERM
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?" SIGINT
while true
  do
    echo "To infinity and beyond"
    sleep 2
  done

