#!/usr/bin/env bash
# Manage my process

start() {
  ./manage_my_process &
  echo $! >> /var/run/my_process.pid
  }

stop() {
  sudo pkill -f -9 "manage_my_process"
  sudo rm /var/run/my_process.pid
  }

case $1 in
  start)
    start
    echo "manage_my_process started"
    ;;
  stop)
    stop
    echo "manage_my_process stopped"
    ;;
  restart)
    stop
    start
    echo 'manage_my_process restarted'
    ;;
esac
  

